### ISSUE TITLE
ingredientRecipe connection

### ISSUE THREAD

**Issue by janjaapbos** [nautilus/recipeBook#3]
I updated my pull request with an ingredientRecipe mutation.

It is not working quite correctly. First of all, when querying ingredientRecipes, only the recipe field is available. There is also a primaryKey field, but no ingredient field.
{ingredientrecipes {
  edges {
    node {
      id
      recipe
      primaryKey
    }
  }
}}

I suppose the recipe field should refer to the recipe ID? (string)

@aaivazis Could you have a look at this? I think something is missing.

**Comment by AlecAivazis** [comment]
Huh, this is probably an issue that belongs on nautilus. mind moving it over there? I'll start looking into it now

**Comment by AlecAivazis** [comment]
i'm gonna close this following our conversation on skype
